version: "3.8"
services:
  store-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgresql://user:password@postgresql:5432/store_db?schema=public
      - NODE_ENV=development
      - APP_SECRET_KEY=83ca8b3e-49bc-4fec-b098-ed22568ec68c
      - AWS_S3_BUCKET=images-bucket
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=user_aws_test
      - AWS_SECRET_ACCESS_KEY=secret_aws_test
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=store_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    expose:
      - '4566'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/var/lib/localstack'
      - './.localstack/.init/:/etc/localstack/init/ready.d/'
      - '/var/run/docker.sock:/var/run/docker.sock'
      
volumes:
  postgres_data: